logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false

pipeline:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json_lines
      }
    }
    output {
      elasticsearch {
        hosts => ["http://quickstart-es-http.elastic.svc:9200"]
        user => "elastic"
        password => "${ELASTIC_PASSWORD}"
      }
    }
